spring:
  datasource:
      driverClassName: org.h2.Driver
      username: sa
      password: password
      url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DATABASE_TO_LOWER=TRUE

#    url: jdbc:mysql://localhost:3306/jdbc_demo?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: KHVvPuDVauw8qn
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
